services:
  app:
    build: .
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "8083:8080"
    depends_on:
      - db
    networks:
      - app-network
    environment:
      - DB_URL=jdbc:mysql://db:3306/testdb
      - DB_USER=root
      - DB_PASSWORD=password

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
    ports:
      - "3307:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
