services:
  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  java-app:
    build: .
    depends_on:
      mysql-db:
        condition: service_healthy  # Ensure MySQL is healthy before starting
    environment:
      DATABASE_URL: jdbc:mysql://mysql-db:3306/mydatabase
      DATABASE_USER: user
      DATABASE_PASSWORD: password
